server:
  port: 9999

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: loginJWT
    password: loginJWT
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  profiles:
    active: local
    include: secret



jwt:
  key:
    access: 64KY64qU7LKc7IOB7J217J2064uk   #나는천상익이다
    refresh: 64KY64qU64uk7Iuc7YOc7Ja064Kc7LKc7IOB7J217J2064uk #나는다시태어난천상익이다
  max-age:
    access: 1800 # 60 * 30
    refresh: 604800 # 60 * 60 * 24 * 7